// Code generated by MockGen. DO NOT EDIT.
// Source: configmaps_test.go

// Package mocks is a generated GoMock package.
package mocks

import (
	cfg "github.com/appuio/seiso/cfg"
	gomock "github.com/golang/mock/gomock"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	reflect "reflect"
	time "time"
)

// MockTestConfigMapResources is a mock of TestConfigMapResources interface
type MockTestConfigMapResources struct {
	ctrl     *gomock.Controller
	recorder *MockTestConfigMapResourcesMockRecorder
}

// MockTestConfigMapResourcesMockRecorder is the mock recorder for MockTestConfigMapResources
type MockTestConfigMapResourcesMockRecorder struct {
	mock *MockTestConfigMapResources
}

// NewMockTestConfigMapResources creates a new mock instance
func NewMockTestConfigMapResources(ctrl *gomock.Controller) *MockTestConfigMapResources {
	mock := &MockTestConfigMapResources{ctrl: ctrl}
	mock.recorder = &MockTestConfigMapResourcesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockTestConfigMapResources) EXPECT() *MockTestConfigMapResourcesMockRecorder {
	return m.recorder
}

// Delete mocks base method
func (m *MockTestConfigMapResources) Delete(resourceSelectorFunc cfg.ResourceNamespaceSelector) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", resourceSelectorFunc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockTestConfigMapResourcesMockRecorder) Delete(resourceSelectorFunc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTestConfigMapResources)(nil).Delete), resourceSelectorFunc)
}

// Print mocks base method
func (m *MockTestConfigMapResources) Print(batch bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Print", batch)
}

// Print indicates an expected call of Print
func (mr *MockTestConfigMapResourcesMockRecorder) Print(batch interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Print", reflect.TypeOf((*MockTestConfigMapResources)(nil).Print), batch)
}

// GetNamespace mocks base method
func (m *MockTestConfigMapResources) GetNamespace() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNamespace")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetNamespace indicates an expected call of GetNamespace
func (mr *MockTestConfigMapResourcesMockRecorder) GetNamespace() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNamespace", reflect.TypeOf((*MockTestConfigMapResources)(nil).GetNamespace))
}

// FilterByTime mocks base method
func (m *MockTestConfigMapResources) FilterByTime(olderThan time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "FilterByTime", olderThan)
}

// FilterByTime indicates an expected call of FilterByTime
func (mr *MockTestConfigMapResourcesMockRecorder) FilterByTime(olderThan interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterByTime", reflect.TypeOf((*MockTestConfigMapResources)(nil).FilterByTime), olderThan)
}

// FilterUsed mocks base method
func (m *MockTestConfigMapResources) FilterUsed() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterUsed")
	ret0, _ := ret[0].(error)
	return ret0
}

// FilterUsed indicates an expected call of FilterUsed
func (mr *MockTestConfigMapResourcesMockRecorder) FilterUsed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterUsed", reflect.TypeOf((*MockTestConfigMapResources)(nil).FilterUsed))
}

// FilterByMaxCount mocks base method
func (m *MockTestConfigMapResources) FilterByMaxCount(keep int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "FilterByMaxCount", keep)
}

// FilterByMaxCount indicates an expected call of FilterByMaxCount
func (mr *MockTestConfigMapResourcesMockRecorder) FilterByMaxCount(keep interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterByMaxCount", reflect.TypeOf((*MockTestConfigMapResources)(nil).FilterByMaxCount), keep)
}

// LoadConfigMaps mocks base method
func (m *MockTestConfigMapResources) LoadConfigMaps(listOptions v1.ListOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadConfigMaps", listOptions)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadConfigMaps indicates an expected call of LoadConfigMaps
func (mr *MockTestConfigMapResourcesMockRecorder) LoadConfigMaps(listOptions interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadConfigMaps", reflect.TypeOf((*MockTestConfigMapResources)(nil).LoadConfigMaps), listOptions)
}

// ListConfigMaps mocks base method
func (m *MockTestConfigMapResources) ListConfigMaps() ([]string, []string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConfigMaps")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].([]string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListConfigMaps indicates an expected call of ListConfigMaps
func (mr *MockTestConfigMapResourcesMockRecorder) ListConfigMaps() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConfigMaps", reflect.TypeOf((*MockTestConfigMapResources)(nil).ListConfigMaps))
}
